name: Frontend-CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Secret
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          echo $ENV > env
          cat env | base64 -di > .env
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag harbor.kafana.dev/ptin/carfe:test || echo "docker build failed"
      - name: Push the Docker image
        run: docker push harbor.kafana.dev/ptin/carfe:test
      - name: Executing Deploy
        run: |
          free -m
          cd /webapps/cars/frontend && ./deploy.sh
